config/routes.rb
Rails.application.routes.draw do

  resources :segments do
    collection {post :import}
  end

  resources :precincts do
    collection {post :import}
  end

  resources :names do
    collection {post :import}
  end

  resources :voters do
    collection {post :generate}
  end

  root to: "segments#index"

end

app/models/name.rb
class Name < ActiveRecord::Base
  require 'CSV'
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      name_hash = row.to_hash
      name = Segment.where(id: name_hash["id"])

      if name.count == 1
        name.first.update_attributes(name_hash)
      else
        Name.create!(name_hash)
      end # end if !name.nil?
    end # end CSV.foreach
  end # end self.import(file)
end #end class

app/controllers/names_controller.rb
class NamesController < ApplicationController
  def index
  	@names = Name.all
  end

  def import
  	Name.import(params[:file])
  	redirect_to action: :index, notice: "Names imported."
  end
end

app/helpers/names_helper.rb
module NamesHelper
end

app/views/names/import.html.erb
<h1>Names#import</h1>
<p>Find me in app/views/names/import.html.erb</p>

app/views/names/index.html.erb
<%= flash[:notice] %>
<table>
  <thead>
    <tr>
      <th>FirstName</th>
      <th>LastName</th>
      <th>MiddleName</th>
      <th>Gender</th>
    </tr>
  </thead>
  <tbody>
    <% @names.each do |name| %>
      <tr>
        <td><%= name.FirstName %></td>
        <td><%= name.LastName %></td>
        <td><%= name.MiddleName %></td>
        <td><%= name.Gender %></td>
    <% end %>
  </tbody>
</table>
<h3>Import a Name CSV File</h3>
  <%= form_tag import_names_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>

<div>
  <br><%= link_to 'Add a Precinct CSV File', precincts_path %><br />
  <br><%= link_to 'Add a Segment CSV File', segments_path %><br />
  <br><%= link_to 'See Voter Roll', voters_path %><br />
</div>