config/routes.rb
Rails.application.routes.draw do

  resources :segments do
    collection {post :import}
  end

  resources :precincts do
    collection {post :import}
  end

  resources :names do
    collection {post :import}
  end

  resources :voters do
    collection {post :generate}
  end

  root to: "segments#index"

end

app/models/segment.rb
class Segment < ActiveRecord::Base
  require 'CSV'
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      segment_hash = row.to_hash
      segment = Segment.where(id: segment_hash["id"])

      if segment.count == 1
        segment.first.update_attributes(segment_hash)
      else
        Segment.create!(segment_hash)
      end # end if !segment.nil?
    end # end CSV.foreach
  end # end self.import(file)
end #end class

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  def index
  	@segments = Segment.all
  end

  def import
  	Segment.import(params[:file])
  	redirect_to action: :index, notice: "Segments imported."
  end
end

app/helpers/segments_helper.rb
module SegmentsHelper
end

app/views/segments/import.html.erb
<h1>Segments#import</h1>
<p>Find me in app/views/segments/import.html.erb</p>

app/views/segments/index.html.erb
<%= flash[:notice] %>
<table>
  <thead>
    <tr>
      <th>StSegUID</th>
      <th>StartHouseNumber</th>
      <th>EndHouseNumber</th>
      <th>OddEvenBoth</th>
      <th>StreetDirection</th>
      <th>StreetName</th>
      <th>StreetSuffix</th>
      <th>PrecinctUID</th>
    </tr>
  </thead>
  <tbody>
    <% @segments.each do |segment| %>
      <tr>
        <td><%= segment.StSegUID %></td>
        <td><%= segment.StartHouseNumber %></td>
        <td><%= segment.EndHouseNumber %></td>
        <td><%= segment.OddEvenBoth %></td>
        <td><%= segment.StreetDirection %></td>
        <td><%= segment.StreetName %></td>
        <td><%= segment.StreetSuffix %></td>
        <td><%= segment.PrecinctUID %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div>
<h3>Import a Segment CSV File</h3>
  <%= form_tag import_segments_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
  <% end %>
</div>
<div>
  <br><%= link_to 'Add a Name CSV File', names_path %><br />
  <br><%= link_to 'Add a Precinct CSV File', precincts_path %></br>
  <br><%= link_to 'See Voter Roll', voters_path %></br>
</div>